default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  username: broota_brazil
  password: broota_brazil

development:
  <<: *default
  database: alpha-blog_development
  host: <%= ENV.fetch('DATABASE_HOST', 'localhost') %>
  username: <%= ENV.fetch('DATABASE_USER', 'broota_brazil') %>
  password: <%= ENV.fetch('DATABASE_PASSWORD', 'broota_brazil') %>

test:
  <<: *default
  database: alpha-blog_test
  host: <%= ENV.fetch('DATABASE_HOST', 'localhost') %>
  username: <%= ENV.fetch('DATABASE_USER', 'broota_brazil') %>
  password: <%= ENV.fetch('DATABASE_PASSWORD', 'broota_brazil') %>

production:
  url:  <%= ENV["DATABASE_URL"] %>
  pool: <%= ENV["DB_POOL"] || ENV['MAX_THREADS'] || 3 %>